---
# tasks file for launch_network_firewall
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: Set the VPC ID
  set_fact:
    vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"

- name: Get the SG info for {{ ec2_name_prefix }}-vpc
  ec2_group_info:
    filters:
      vpc-id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
  register: group_info

- name: Select Public SG
  set_fact:
    public_group_id: "{{ group_info.security_groups | json_query(group_query) }}"
  vars:
    group_query: "[?group_name=='{{ ec2_name_prefix }}-Public-SG'].group_id"

- name: Select Private SG
  set_fact:
    private_group_id: "{{ group_info.security_groups | json_query(group_query) }}"
  vars:
    group_query: "[?group_name=='{{ ec2_name_prefix }}-Private-SG'].group_id"

- name: Get the subnet info for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
  register: subnet_info

- name: Select Public Subnet ID
  set_fact:
    public_subnet_id: "{{ subnet_info.subnets | json_query(subnet_query) | first }}"
  vars:
    subnet_query: "[?tags.Name=='{{ ec2_name_prefix }}-Public-{{ zone }}'].subnet_id"

- name: Select Private Subnet ID
  set_fact:
    private_subnet_id: "{{ subnet_info.subnets | json_query(subnet_query) | first }}"
  vars:
    subnet_query: "[?tags.Name=='{{ ec2_name_prefix }}-Private-{{ zone }}'].subnet_id"

- name: "Find current, region-specific AMI."
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ami_name }}"
  register: found_amis

- name: "Set AMI value"
  set_fact:
    target_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  when: found_amis.images is defined

- name: "Start instance."
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
    image: "{{ target_ami.image_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ public_group_id }}"
    vpc_subnet_id: "{{ public_subnet_id }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag: 
      Name: "{{ ec2_name_prefix }} Firewall {{ item }}"
    instance_tags:
      Role: firewall
      Platform: ASA
      Name: "{{ ec2_name_prefix }} Firewall {{ item }}"
      Inventory: "{{ ec2_name_prefix }}"
      Stage: "instantiated"
  loop: "{{ range(1, instance_count +1)|list }}"
  loop_control:
    label: "{{ item }}"
  register: ec2

- name: attach eni for private subnet
  amazon.aws.ec2_eni:
    instance_id: "{{ item[id] }}"
    subnet_id: "{{ private_subnet_id }}"
    security_groups: "{{ private_group_id }}"
    state: present
  loop: "{{ ec2.tagged_instances }}"
  loop_control:
    label: "{{ item[id] }}"

- name: "Wait for connection on all hosts."
  wait_for:
    host: "{{ item['tagged_instances'][0]['private_ip'] }}"
    port: 22
    timeout: 600
  loop: "{{ ec2.results }}"
  loop_control:
    label: "{{ item['tagged_instances'][0]['private_ip'] }}"