---
# tasks file for launch_network_firewall
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: Get the SG ID for {{ ec2_name_prefix }}-sg
  ec2_group_info:
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
#      group-name: "{{ ec2_name_prefix }}-sg"
    region: "{{ ec2_region }}"
  register: sg_net_facts

- name: Get the subnet ID for {{ ec2_name_prefix }}-subnet
  ec2_vpc_subnet_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
#      "tag:Name": "{{ ec2_name_prefix }}-subnet"
  register: subnet_info

- name: "Find current, region-specific AMI ID."
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ami_name }}"
  register: found_amis

- name: "Set AMI value"
  set_fact:
    target_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  when: found_amis.images is defined

- name: "Start instance."
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
    image: "{{ target_ami.image_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ sg_net_facts.security_groups[0].group_id }}"
    vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
    wait: yes
    wait_timeout: 500
    exact_count: "{{ instance_count }}"
    count_tag: 
      Name: "{{ ec2_name_prefix }} Firewall"
    instance_tags:
      Role: firewall
      Platform: ASA
      Name: "{{ ec2_name_prefix }} Firewall"
      Inventory: "{{ ec2_name_prefix }}"
      Stage: "instantiated"
  register: ec2_result

- name: "Wait for connection on all hosts."
  wait_for:
    port: 22
    host: "{{ item.private_ip }}"
    timeout: 600
  loop: "{{ ec2_result.instances }}"
